cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]

c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]

vc:
  - 14

c_compiler_version:     # [osx]
  - "*"                 # [osx]

cxx_compiler_version:   # [osx]
  - "*"                 # [osx]

variant:
  - default
  - hcc   # [linux]
  - root_62600  # [linux or osx]
  - cling_v0.9  # Tag is cling-v0.9

# ROOT uses the cling variant of llvm
llvm_variant:
  - default
  - default    # [linux]
  - cling_v0.9  # [linux or osx]
  - cling_v0.9

zip_keys:
  -
    - variant
    - llvm_variant
